"""Generate committed language bindings from the public Pydantic contracts."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from gateway.public_contracts import build_public_contract_schema


SCHEMA_PATH = ROOT / "contracts" / "runtime-v1.schema.json"
TYPESCRIPT_PATH = ROOT / "UI" / "src" / "generated" / "public-contracts.ts"
SDK_TYPESCRIPT_PATH = (
    ROOT / "sdk" / "typescript" / "src" / "generated" / "public-contracts.ts"
)


def _ts_type(schema: Dict[str, Any]) -> str:
    if "$ref" in schema:
        return str(schema["$ref"]).rsplit("/", 1)[-1]

    if "enum" in schema:
        return " | ".join(json.dumps(value, ensure_ascii=False) for value in schema["enum"])

    variants = schema.get("anyOf") or schema.get("oneOf")
    if variants:
        return " | ".join(_ts_type(item) for item in variants)

    schema_type = schema.get("type")
    if schema_type == "string":
        return "string"
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "null":
        return "null"
    if schema_type == "array":
        item_type = _ts_type(schema.get("items") or {})
        return f"Array<{item_type}>"
    if schema_type == "object" or "properties" in schema or "additionalProperties" in schema:
        properties = schema.get("properties") or {}
        if properties:
            required = set(schema.get("required") or [])
            rows = []
            for name, value in properties.items():
                optional = "" if name in required else "?"
                rows.append(f"{json.dumps(name)}{optional}: {_ts_type(value)}")
            return "{ " + "; ".join(rows) + " }"
        additional = schema.get("additionalProperties")
        value_type = _ts_type(additional) if isinstance(additional, dict) else "unknown"
        return f"Record<string, {value_type}>"
    return "unknown"


def render_typescript(schema: Dict[str, Any]) -> str:
    rows = [
        "// AUTO-GENERATED. DO NOT EDIT MANUALLY.",
        "// Generated by scripts/generate_public_contracts.py.",
        "// Source: gateway/public_contracts.py",
        "",
    ]
    for name, definition in schema["$defs"].items():
        if definition.get("type") == "object" or "properties" in definition:
            required = set(definition.get("required") or [])
            rows.append(f"export interface {name} {{")
            if definition.get("additionalProperties") is True:
                rows.append("  [key: string]: unknown")
            for field_name, field_schema in (definition.get("properties") or {}).items():
                optional = "" if field_name in required else "?"
                rows.append(f"  {field_name}{optional}: {_ts_type(field_schema)}")
            rows.append("}")
        else:
            rows.append(f"export type {name} = {_ts_type(definition)}")
        rows.append("")
    return "\n".join(rows)


def render_schema(schema: Dict[str, Any]) -> str:
    return json.dumps(schema, ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def generated_artifacts() -> Dict[Path, str]:
    schema = build_public_contract_schema()
    return {
        SCHEMA_PATH: render_schema(schema),
        TYPESCRIPT_PATH: render_typescript(schema),
        SDK_TYPESCRIPT_PATH: render_typescript(schema),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when generated files are stale")
    args = parser.parse_args()

    stale = []
    for path, expected in generated_artifacts().items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != expected:
                stale.append(path)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected, encoding="utf-8", newline="\n")

    if stale:
        for path in stale:
            print(f"stale generated contract: {path.relative_to(ROOT)}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
